# 默认配置请参考 config/__init__.py
name: base

## model
### model_provider, option in deepseek, zhipu
model_provider: zhipu
model_name: null # for default

## model dir 可以写相对路径和绝对路径
### 相对路径是相对于环境变量 (.env) 中 MODEL_ROOT_DIR 的路径
model_local_paths:
  bge-large-zh-v1.5: bge-large-zh-v1.5
  oneke: oneke